# Samsung Galaxy Note3
add_lunch_combo cmremix_hlte-userdebug
add_lunch_combo cmremix_hltetmo-userdebug
add_lunch_combo cmremix_hltespr-userdebug
add_lunch_combo cmremix_hltevzw-userdebug
add_lunch_combo cmremix_hlteusc-userdebug
# Samsung Galaxy Note4
add_lunch_combo cmremix_trlteeur-userdebug
add_lunch_combo cmremix_trltetmo-userdebug
add_lunch_combo cmremix_trltespr-userdebug
add_lunch_combo cmremix_trlteusc-userdebug
add_lunch_combo cmremix_trltevzw-userdebug
# Sony Xperia Z Ultra
add_lunch_combo cmremix_togari-userdebug
# Motorola
add_lunch_combo cmremix_falcon-userdebug
add_lunch_combo cmremix_titan-userdebug
# Sprout
add_lunch_combo cmremix_sprout4-userdebug
add_lunch_combo cmremix_sprout8-userdebug
# OnePlus One
add_lunch_combo cmremix_bacon-userdebug
# LGE G3
add_lunch_combo cmremix_ls990-userdebug

